spring.application.name=e-commerce-api

# ================= SERVER =================
server.servlet.context-path=/api

# =========== DATABASE (PostgreSQL) ===========
spring.datasource.url=jdbc:postgresql://localhost:3307/db_e_commerce
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ================= ORM (JPA/Hibernate) =================
# Tự động đồng bộ cấu trúc bảng (update, validate, create, create-drop, none)
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu lệnh SQL trong Console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dùng tên column đúng như khai báo trong @Column(name=...), không tự lowercase
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Bắt buộc Hibernate quote tất cả identifier → PostgreSQL xử lý đúng "Id", "Email"...
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.jpa.open-in-view=false

# JWT
fss.jwt.access-secret=aa57bb2618890d253e4187411c10edfe4977d592e16d4e374cc8c9632a977526
# 15 phút
fss.jwt.access-expiration=900000
fss.jwt.refresh-secret=4b3e67d85aa98d6f47b932f5e5f06f67e92689a6e4f518624aa94f4d1c34a2e7
# 7 ngày
fss.jwt.refresh-expiration=604800000

# LOGGING
spring.output.ansi.enabled=always
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
